[package]
name = "checkyoself"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
blake3 = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
indicatif = "0.17"
colored = "2"
